services:
  Jose-MQ:
    build: ./Jose-MQ
    container_name: Jose-MQ
  
  Alejandro:
    build: ./Alejandro
    container_name: Alejandro

services:
  PedroMarcos:
    build: ./PedroMarcos
    container_name: marcos-container

services:
Salvador:
build: ./Equipo/Salvamoli
container_name: salvamoli-contenedor
